version: 2

jobs:
  build:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:14.17.0
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/pokematchup
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run: npm ci
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Running Unit tests with Jest
          command: npm run test
      - run:
          name: Start the server before running E2E Tests
          command: npm start
          background: true
      - run:
          name: Running E2E tests with JUnit reporter
          command: npm run cypress:junit
      - store_test_results:
          path: junit-results
      - store_artifacts:
          path: src/cypress/videos
      - store_artifacts:
          path: src/cypress/screenshots